### ISSUE TITLE
ChatPerson compression throwing type errors

### ISSUE THREAD

**Issue by alamorre** [chatengine-io/react-chat-engine-components#22]
<img width="1440" alt="Screen Shot 2021-11-14 at 12 38 55 PM" src="https://user-images.githubusercontent.com/15023107/141697782-715ee879-dc03-4d67-961e-7ec64259900c.png">

Seems like the `ChatPerson` interface compression is throwing errors in `Message/index.tsx` can you look into this and make some patch for it?

Interesting our tests pass and these issue still live. Clear calling for us to beef up our Jest game

**Comment by dhavelock** [comment]
hmmm looking into it now
