### ISSUE TITLE
Make an ArgsTable for customStyle

### ISSUE THREAD

**Issue by alamorre** [chatengine-io/react-chat-engine-components#28]
Pre-requisite: 
- https://github.com/chatengine-io/react-chat-engine-components/issues/24
- https://github.com/chatengine-io/react-chat-engine-components/issues/29

Basically we need to standardize and enhance the customStyle documentation. Consistency, color-way to easily to understand whats what in the interface, and the args table to really spell it out for people.

**Comment by dhavelock** [comment]
- ordering the props
- breaking up styles into separate tables perhaps

**Comment by alamorre** [comment]
Seems like we've done this now in various PRs over time
