### ISSUE TITLE
Fix ChatForm button

### ISSUE THREAD

**Issue by alamorre** [chatengine-io/react-chat-engine-components#33]
It's stuck to the left right now and looks funny.

**Comment by dhavelock** [comment]
what'a the issue?

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/17277946/142095977-dda8bc55-9908-4fc1-b21a-85651ca0ec5a.png">

**Comment by alamorre** [comment]
Ah I think my new PR messes with it then

**Comment by alamorre** [comment]
Finishing it off and we'll need to review it today or tmo depending on timing
